server:
  port: 8001

mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.uzhizhe.micorservice.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: uzhizhe-microservice-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver        # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/uzhizhe-micorservice?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&transformedBitIsBoolean=true&useSSL=false              # 数据库名称
    username: root
    password: root1223
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: uzhizhe-microservice-provider
  company.name: www.uzhizhe.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


logging:
  level:
    com.uzhizhe.microservice.dao: debug
    org.mybatis: debug


